name: GraphAligner
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_9
  - boost=1.67.0=py36h3e44d54_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - gcc_impl_linux-64=11.2.0=h82a94d6_15
  - gcc_linux-64=11.2.0=h39a9532_9
  - gxx_impl_linux-64=11.2.0=h82a94d6_15
  - gxx_linux-64=11.2.0=hacbe6df_9
  - icu=58.2=hf484d3e_1000
  - jemalloc=5.2.0=he1b5a44_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=14_linux64_openblas
  - libboost=1.67.0=h46d08c1_4
  - libcblas=3.9.0=14_linux64_openblas
  - libdivsufsort=2.0.2=hec16e2b_5
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=11.2.0=h0952999_15
  - libgcc-ng=11.2.0=h1d223b6_15
  - libgfortran-ng=11.2.0=h69a702a_15
  - libgfortran5=11.2.0=h5c6108e_15
  - libgomp=11.2.0=h1d223b6_15
  - liblapack=3.9.0=14_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libprotobuf=3.14.0=h780b84a_0
  - libprotobuf-static=3.14.0=ha770c72_0
  - libsanitizer=11.2.0=he4da1e4_15
  - libstdcxx-devel_linux-64=11.2.0=h0952999_15
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libzlib=1.2.11=h166bdaf_1014
  - make=4.3=hd18ef5c_1
  - ncurses=6.3=h27087fc_1
  - numpy=1.19.5=py36hfc0c790_2
  - openssl=1.1.1n=h166bdaf_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - protobuf=3.14.0=py36hc4f0c31_1
  - python=3.6.15=hb7a2778_0_cpython
  - python_abi=3.6=2_cp36m
  - readline=8.1=h46c0cb4_0
  - sdsl-lite=2.1.1=h4bd325d_1002
  - setuptools=58.0.4=py36h5fab9bb_2
  - six=1.16.0=pyh6c4a22f_0
  - sparsehash=2.0.4=h9c3ff4c_0
  - sqlite=3.38.2=h4ff8645_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
prefix: /home/rautiainenma/miniconda3/envs/GraphAligner
