### Change these!!
GenomeSize: 4600000
ShortreadCoverage: 200

ShortReadDirectory: shortreads/
ShortReads:
- reads1.fq
- reads2.fq.gz

LongReadDirectory: longreads/
LongReads:
- reads1.fq
- reads2.fq.gz

TempDirectory: tmp/
OutputDirectory: output/

# https://github.com/maickrau/GraphAligner
GraphAlignerBinDirectory: ../../bin/
# https://github.com/GATB/bcalm
BcalmPath: bcalm/bin/bcalm
BcalmConvertPath: bcalm/scripts/convertToGFA.py
# https://github.com/mourisl/Lighter
LighterPath: lighter/lighter


### Misc params. Defaults might work

# k for error correcting the reads. Try between 10-20
SmallK: 11
# k for the de Bruijn graph. Try between ~1/2 and ~2/3 of short read length
BigK: 61
# minimum k-mer abundance for the de Bruijn graph. Try around ~1/100 of short read coverage, but not below 2.
Abundance: 2
